disableEmailVerification: true

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 480333526007543
            client-secret: 27fc07fcb10976229e6c0449738880b7

logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO