server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          crypto-portfolio:
            client-id: crypto-portfolio
            client-secret: 51bc9b20-eb9d-4541-a6b6-1d14692559e9
            client-name: Crypto Portfolio
            scope: openid,profile,email,offline_access
            redirect-uri: http://localhost:8081/login/oauth2/code/crypto-portfolio
            provider: crypto-provider           
        provider:
          crypto-provider:
            issuer-uri: http://localhost:8080/auth/realms/CryptoInc
            #token-uri: http://localhost:8081/auth/realms/CryptoInc/protocol/openid-connect/token
            #authorization-uri: http://localhost:8081/auth/realms/CryptoInc/protocol/openid-connect/auth
            #user-info-uri: http://localhost:8081/auth/realms/CryptoInc/protocol/openid-connect/userinfo
            #user-name-attribute: sub
            #jwk-set-uri: http://localhost:8081/auth/realms/CryptoInc/protocol/openid-connect/certs
            
  
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO